SYMBOLS = [
    "BTC/USDT:USDT",
    "ETH/USDT:USDT",
    "SOL/USDT:USDT",
    "XRP/USDT:USDT",
    "BNB/USDT:USDT",
    "ADA/USDT:USDT",
    "DOGE/USDT:USDT",
    "LINK/USDT:USDT",
    "AVAX/USDT:USDT",
]

TIMEFRAME_FAST = "5m"
TIMEFRAME_CONTEXT = "15m"
CANDLE_LIMIT = 120

TOP_SETUPS = 5
LOOP_INTERVAL_SECONDS = 300
SIGNAL_DEDUP_MINUTES = 30

RSI_PERIOD = 14
ZSCORE_PERIOD = 20
VWAP_WINDOW = 20

RSI_LONG_MAX = 31
RSI_SHORT_MIN = 69
CONTEXT_LONG_MAX = 41
CONTEXT_SHORT_MIN = 59

VWAP_STRETCH_MIN = 0.0030
ZSCORE_MIN = 0.65

SCORE_MIN = 0.82
