SYMBOLS = [
    "BTC/USDT:USDT",
    "ETH/USDT:USDT",
    "SOL/USDT:USDT",
    "XRP/USDT:USDT",
]

TIMEFRAME_FAST = "5m"
TIMEFRAME_CONTEXT = "15m"
CANDLE_LIMIT = 120

TOP_SETUPS = 5
LOOP_INTERVAL_SECONDS = 300

RSI_PERIOD = 14
ZSCORE_PERIOD = 20
VWAP_WINDOW = 20

RSI_LONG_MAX = 35
RSI_SHORT_MIN = 65
CONTEXT_LONG_MAX = 45
CONTEXT_SHORT_MIN = 55

VWAP_STRETCH_MIN = 0.0015
ZSCORE_MIN = 0.25

SCORE_MIN = 0.55
